# Generated by Django 2.1 on 2018-08-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_volunteer_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='area',
            field=models.CharField(choices=[('dcr', 'Doctor'), ('hsv', 'Health Services'), ('elw', 'Electrical Works'), ('mew', 'Mechanical Work'), ('cvw', 'Civil Work'), ('plw', 'Plumbing work'), ('vls', 'Vehicle Support'), ('ckg', 'Cooking'), ('rlo', 'Relief operation'), ('cln', 'Cleaning'), ('oth', 'Other')], default='oth', max_length=15, verbose_name='Area of volunteering'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contributor',
            name='commodities',
            field=models.TextField(verbose_name='What you can contribute. ( സംഭാവന ചെയ്യാന്\u200d ഉദ്ദേശിക്കുന്ന സാധനങ്ങള്\u200d ) -- Eg: Shirts, torches etc '),
        ),
        migrations.AlterField(
            model_name='request',
            name='detailcloth',
            field=models.CharField(blank=True, max_length=250, verbose_name='Details for required clothing - ആവശ്യമായ വസ്ത്രത്തിന്\u200dറെ വിവരങ്ങള്\u200d'),
        ),
        migrations.AlterField(
            model_name='request',
            name='detailfood',
            field=models.CharField(blank=True, max_length=250, verbose_name='Details for required food - ആവശ്യമായ ഭക്ഷണത്തിന്\u200dറെ വിവരങ്ങള്\u200d'),
        ),
        migrations.AlterField(
            model_name='request',
            name='detailkit_util',
            field=models.CharField(blank=True, max_length=250, verbose_name='Details for required kitchen utensil - ആവശ്യമായ അടുക്കള സാമഗ്രികള്\u200d'),
        ),
        migrations.AlterField(
            model_name='request',
            name='detailmed',
            field=models.CharField(blank=True, max_length=250, verbose_name='Details for required medicine - ആവശ്യമായ മരുന്നിന്\u200dറെ  വിവരങ്ങള്\u200d'),
        ),
        migrations.AlterField(
            model_name='request',
            name='detailtoilet',
            field=models.CharField(blank=True, max_length=250, verbose_name='Details for required toiletries - ആവശ്യമായ  ശുചീകരണ സാമഗ്രികള്\u200d'),
        ),
        migrations.AlterField(
            model_name='request',
            name='detailwater',
            field=models.CharField(blank=True, max_length=250, verbose_name='Details for required water - ആവശ്യമായ വെള്ളത്തിന്\u200dറെ വിവരങ്ങള്\u200d'),
        ),
        migrations.AlterField(
            model_name='request',
            name='district',
            field=models.CharField(choices=[('tvm', 'Thiruvananthapuram'), ('ptm', 'Pathanamthitta'), ('alp', 'Alappuzha'), ('ktm', 'Kottayam'), ('idk', 'Idukki'), ('mpm', 'Malappuram'), ('koz', 'Kozhikode'), ('wnd', 'Wayanad'), ('knr', 'Kannur'), ('ksr', 'Kasaragod'), ('pkd', 'Palakkad'), ('tcr', 'Thrissur'), ('ekm', 'Ernakulam'), ('kol', 'Kollam')], max_length=15, verbose_name='Districts - ജില്ല'),
        ),
        migrations.AlterField(
            model_name='request',
            name='location',
            field=models.CharField(max_length=500, verbose_name='Location - സ്ഥലം'),
        ),
        migrations.AlterField(
            model_name='request',
            name='needcloth',
            field=models.BooleanField(verbose_name='Clothing - വസ്ത്രം'),
        ),
        migrations.AlterField(
            model_name='request',
            name='needfood',
            field=models.BooleanField(verbose_name='Food - ഭക്ഷണം'),
        ),
        migrations.AlterField(
            model_name='request',
            name='needkit_util',
            field=models.BooleanField(verbose_name='Kitchen utensil - അടുക്കള സാമഗ്രികള്\u200d'),
        ),
        migrations.AlterField(
            model_name='request',
            name='needmed',
            field=models.BooleanField(verbose_name='Medicine - മരുന്നുകള്\u200d'),
        ),
        migrations.AlterField(
            model_name='request',
            name='needothers',
            field=models.CharField(blank=True, max_length=500, verbose_name='Other needs - മറ്റു ആവശ്യങ്ങള്\u200d'),
        ),
        migrations.AlterField(
            model_name='request',
            name='needtoilet',
            field=models.BooleanField(verbose_name='Toiletries - ശുചീകരണ സാമഗ്രികള്\u200d '),
        ),
        migrations.AlterField(
            model_name='request',
            name='needwater',
            field=models.BooleanField(verbose_name='Water - വെള്ളം'),
        ),
        migrations.AlterField(
            model_name='request',
            name='requestee',
            field=models.CharField(max_length=100, verbose_name='Requestee - അപേക്ഷകന്\u200dറെ പേര്'),
        ),
        migrations.AlterField(
            model_name='request',
            name='requestee_phone',
            field=models.CharField(max_length=10, verbose_name='Requestee Phone - അപേക്ഷകന്\u200dറെ ഫോണ്\u200d നമ്പര്\u200d'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='organisation',
            field=models.CharField(max_length=250, verbose_name='Organization (സംഘടന) / Institution'),
        ),
    ]
