# Generated by Django 2.1 on 2018-08-16 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_auto_20180816_1347'),
        ('mainapp', '0025_auto_20180816_1203'),
    ]

    operations = [
    ]
