# Generated by Django 2.1 on 2018-08-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_merge_20180816_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='detailrescue',
            field=models.CharField(blank=True, max_length=250, verbose_name='Details for rescue action - രക്ഷാപ്രവർത്തനം വിവരങ്ങള്'),
        ),
        migrations.AddField(
            model_name='request',
            name='needrescue',
            field=models.BooleanField(default=False, verbose_name='Need rescue - രക്ഷാപ്രവർത്തനം ആവശ്യമുണ്ട്'),
            preserve_default=False,
        ),
    ]
