# Generated by Django 2.1 on 2018-08-16 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_request_is_request_for_others'),
        ('mainapp', '0027_auto_20180816_1801'),
    ]

    operations = [
    ]
