# Generated by Django 2.1 on 2018-08-16 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0027_rescuecampdetails'),
        ('mainapp', '0028_merge_20180816_1824'),
    ]

    operations = [
    ]
