# Generated by Django 2.1 on 2018-08-16 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_rescuecamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Others')], verbose_name='Gender')),
                ('address', models.CharField(max_length=150)),
                ('district', models.CharField(choices=[('tvm', 'Thiruvananthapuram'), ('ptm', 'Pathanamthitta'), ('alp', 'Alappuzha'), ('ktm', 'Kottayam'), ('idk', 'Idukki'), ('mpm', 'Malappuram'), ('koz', 'Kozhikode'), ('wnd', 'Wayanad'), ('knr', 'Kannur'), ('ksr', 'Kasaragod'), ('pkd', 'Palakkad'), ('tcr', 'Thrissur'), ('ekm', 'Ernakulam'), ('kol', 'Kollam')], max_length=15, verbose_name='Districts')),
                ('phone', models.CharField(max_length=11)),
                ('notes', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='rescuecamp',
            name='location',
            field=models.TextField(verbose_name='Location - Eg: Kalamassery'),
        ),
        migrations.AlterField(
            model_name='rescuecamp',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name - Eg: CUSAT University SOE'),
        ),
        migrations.AddField(
            model_name='person',
            name='camped_at',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.RescueCamp'),
        ),
    ]
