# Generated by Django 2.1 on 2018-08-16 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0031_auto_20180817_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rescuecamp',
            name='contacts',
            field=models.TextField(blank=True, null=True, verbose_name='Phone Numbers'),
        ),
        migrations.AlterField(
            model_name='rescuecamp',
            name='location',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
    ]
