# Generated by Django 2.1 on 2018-08-16 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0031_auto_20180817_0000'),
        ('mainapp', '0029_merge_20180816_2112'),
    ]

    operations = [
    ]
