# Generated by Django 2.1 on 2018-08-17 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0032_auto_20180817_0444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rescuecamp',
            options={'verbose_name': 'Relief Camp'},
        ),
    ]
