# Generated by Django 2.1 on 2018-08-17 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0032_auto_20180817_0444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rescuecamp',
            options={'verbose_name': 'Relief Camp'},
        ),
        migrations.AddField(
            model_name='rescuecamp',
            name='latlng',
            field=models.CharField(blank=True, max_length=100, verbose_name='GPS Coordinates - GPS നിർദ്ദേശാങ്കങ്ങൾ '),
        ),
    ]
