# Generated by Django 2.1 on 2018-08-16 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0033_auto_20180817_0225'),
        ('mainapp', '0033_auto_20180817_0235'),
    ]

    operations = [
    ]
