# Generated by Django 2.1 on 2018-08-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0033_auto_20180817_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='rescuecamp',
            name='taluk',
            field=models.CharField(default=' ', max_length=50, verbose_name='Taluk'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rescuecamp',
            name='village',
            field=models.CharField(default=' ', max_length=50, verbose_name='Village'),
            preserve_default=False,
        ),
    ]
