# Generated by Django 2.1 on 2018-08-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0033_auto_20180817_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='rescuecamp',
            name='map_link',
            field=models.TextField(blank=True, null=True, verbose_name='Map link'),
        ),
    ]
