# Generated by Django 2.1 on 2018-08-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0034_ngo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='area',
            field=models.TextField(verbose_name='Area of volunteering'),
        ),
    ]
