# Generated by Django 2.1 on 2018-08-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0034_rescuecamp_map_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='Address - വിലാസം'),
        ),
    ]
