# Generated by Django 2.1 on 2018-08-17 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0034_auto_20180817_1206'),
        ('mainapp', '0034_auto_20180817_1337'),
    ]

    operations = [
    ]
