# Generated by Django 2.1 on 2018-08-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0035_auto_20180817_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rescuecamp',
            name='map_link',
            field=models.CharField(blank=True, help_text='Copy and paste the full Google Maps link', max_length=250, null=True, verbose_name='Map link'),
        ),
    ]
