# Generated by Django 2.1 on 2018-08-17 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0035_merge_20180817_1449'),
        ('mainapp', '0036_auto_20180817_1500'),
    ]

    operations = [
    ]
