# Generated by Django 2.1 on 2018-08-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0037_merge_20180817_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='rescuecamp',
            name='clothing_req',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rescuecamp',
            name='food_req',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rescuecamp',
            name='medical_req',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rescuecamp',
            name='other_req',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rescuecamp',
            name='sanitary_req',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
