# Generated by Django 2.1 on 2018-08-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0038_auto_20180817_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rescuecamp',
            name='clothing_req',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rescuecamp',
            name='food_req',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rescuecamp',
            name='medical_req',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rescuecamp',
            name='other_req',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rescuecamp',
            name='sanitary_req',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
