# Generated by Django 2.1 on 2018-08-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0039_auto_20180817_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rescuecamp',
            name='clothing_req',
            field=models.TextField(blank=True, null=True, verbose_name='Clothing - വസ്ത്രം'),
        ),
        migrations.AlterField(
            model_name='rescuecamp',
            name='contacts',
            field=models.TextField(blank=True, null=True, verbose_name='Phone Numbers - ഫോൺ നമ്പറുകൾ'),
        ),
        migrations.AlterField(
            model_name='rescuecamp',
            name='food_req',
            field=models.TextField(blank=True, null=True, verbose_name='Food - ഭക്ഷണം'),
        ),
        migrations.AlterField(
            model_name='rescuecamp',
            name='location',
            field=models.TextField(blank=True, null=True, verbose_name='Address - അഡ്രസ്'),
        ),
        migrations.AlterField(
            model_name='rescuecamp',
            name='medical_req',
            field=models.TextField(blank=True, null=True, verbose_name='Medical - മെഡിക്കൽ'),
        ),
        migrations.AlterField(
            model_name='rescuecamp',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Camp Name - ക്യാമ്പിന്റെ പേര്'),
        ),
        migrations.AlterField(
            model_name='rescuecamp',
            name='other_req',
            field=models.TextField(blank=True, null=True, verbose_name='Other - മറ്റുള്ളവ'),
        ),
        migrations.AlterField(
            model_name='rescuecamp',
            name='sanitary_req',
            field=models.TextField(blank=True, null=True, verbose_name='Sanitary - സാനിറ്ററി'),
        ),
        migrations.AlterField(
            model_name='rescuecamp',
            name='taluk',
            field=models.CharField(max_length=50, verbose_name='Taluk - താലൂക്ക്'),
        ),
        migrations.AlterField(
            model_name='rescuecamp',
            name='village',
            field=models.CharField(max_length=50, verbose_name='Village - വില്ലജ്'),
        ),
    ]
