# Generated by Django 2.1 on 2018-08-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pickup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobilenumber', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('latt', models.IntegerField()),
                ('long', models.IntegerField()),
                ('medicalemergency', models.BooleanField(default=False)),
                ('medicalreason', models.TextField()),
                ('no_people', models.IntegerField()),
            ],
        ),
    ]
