# Generated by Django 2.1 on 2018-08-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restendpoint', '0002_auto_20180816_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickup',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pickup',
            name='medicalemergency',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='pickup',
            name='medicalreason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pickup',
            name='mobilenumber',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='pickup',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pickup',
            name='no_people',
            field=models.IntegerField(blank=True),
        ),
    ]
